### PR TITLE
Custom Character Script

### PR DESCRIPTION
**Pull request by BertovDev**
This PR:

- Creates a script called `CustomCharacter` its a extend of the `Character` class but with a custom reference called `CharacterBase`
- Creates a new Prefab called `CharacterBase` where we have all the common prefabs for all characters such as PlayerName, FeedbackContainer, hitbox, etc...
- Changes all the `Character` references in the project to `CustomCharacter`

With this change we can access to the references so much easier. Avoiding methods calls like Find, CompareTag, FindByName etc..

How to create a new Character
- Add customCharacter Script
    - In the editor in CustomCharacter script Set playerID to Player1 also assing the Animator, characterModel,HealthComp.
    - Add the characterBase prefab as a child and then assing it to the characterBase in characterBase
    - Assing and adjust values of the components inside characterBase prefab

This is a simple toturial, further explanation can be made later in the docs.

### CODE REVIEW

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Delete Character component from H4ck.prefab

**Review by AngieDutra — APPROVED** [review]
LGTM! ✨

**Review by ncontinanza — APPROVED** [review]
Great job!

**Review by AngieDutra — APPROVED** [review]
still looking good ;)

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
