### PR TITLE
Bot movement

### LINKED ISSUE #355: [FEATURE] Add agressive bot
Add a simple AI to bots that make them move and try to attack adjacent players

### PR DESCRIPTION
**Pull request by AminArria**
Part of #355 

- [x] Bot moves randomly
- [x] Button to enable/disable bot actions

In next PR
- [ ] Bot moves random or towards player
- [ ] Bot attacks nearby players
- [ ] Random selection of character for bots

### CODE REVIEW

**Comment by BertovDev** [comment]
Nice ! I think it would be good to add a toggle button for the bot movement. We can do that in other PR

**Review by ncontinanza — CHANGES_REQUESTED** [review]
Nice job! Just one detail I noticed: while the bots are moving, it is impossible to damage them by attacking, and they do not perform the animation of receiving an attack.

**Comment by AminArria** [comment]
>  toggle button for the bot movement.

@BertovDev added it to my todo list, for now I also included a "no movement" in the random so it can happen they stay still

> impossible to damage them by attacking

@ncontinanza seems this is related to how fast the bot gets and sends updates vs the client, I think the bot is just too in the future or the client is too in the past and we have no way to compensate for this. For now I slowed the bot a bit (further slowed would mess with the movement for some reason) and it seems more damageable, let me know how you feel it

**Review by ncontinanza — APPROVED** [review]

**Review by BertovDev — COMMENTED** [review]
Awesome! The only thing is that the bots are pretty difficult to hit. ( It simulate real game behaviour really well which is awesome ) but it might be a disadvantages for quick testings.

I think it would be better to merge it when the no movement feature is implemented.
What do you think?

**Comment by tvillegas98** [comment]
> Awesome! The only thing is that the bots are pretty difficult to hit. ( It simulate real game behaviour really well which is awesome ) but it might be a disadvantages for quick testings.
> 
> I think it would be better to merge it when the no movement feature is implemented. What do you think?

Maybe what we can add are buttons to toggle on the movement or the attack

**Comment by tvillegas98** [comment]
This is working very well, I test it with 9 bots and each one of them moved around the map 😛  and also, I was able to hit each one of them

**Review by tvillegas98 — APPROVED** [review]

**Review by BertovDev — APPROVED** [review]
Toggle Bot button works perfect, so nice!

**Pull request merged**
