### PR TITLE
Button selection UI UX

### PR DESCRIPTION
**Pull request by AngieDutra**
This PR:

- Adds a button selection style
- Fixes joysticks and pause button position
- Cooldown font changes

Note: Check settings buttons work was expected since there were changes in the backend playground scene

### CODE REVIEW

**Review by ncontinanza — APPROVED** [review]
Works great!

**Comment by mgrunwaldt** [comment]
Testing this pr I got this issue, not sure if related to this pr though

https://github.com/lambdaclass/curse_of_myrra/assets/22064054/5e06773a-03f1-47df-951b-a735ed05c419

**Comment by BertovDev** [comment]
> 

This is because it doesnt have main merged. I will push the commit to fix it. Nice 🤩

**Comment by BertovDev** [comment]
> Testing this pr I got this issue, not sure if related to this pr though
> Grabacion.de.pantalla.2023-08-04.a.la.s.11.46.06.mov

This is because it doesnt have main merged. I will push the commit to fix it. Nice 🤩

**Review by saugon — DISMISSED** [review]

**Review by ncontinanza — APPROVED** [review]

**Review by BertovDev — APPROVED** [review]
Awesome! 🤩

**Review by saugon — APPROVED** [review]

**Pull request merged**
