### PR TITLE
Add template for pull-requests descriptions

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
Sometimes the PRs descriptions don't give you enough context or explain more than it should.
With a template we standardize what we want to tell to the reviewers about the PR.

### CODE REVIEW

**Comment by martinacantaro** [comment]
Nice addition, should be the standard for all projects.

To clarify, the author of this PR should provide info on how he/she tested it? Or is this section intended to provide info to the reviewers on how to test it? (if not, I would add a section with that purpose)

> ## How has this been tested?
> Describe the steps you performed to test this PR.

Also, what is the goal of self-reviewing? Making sure you didn't make a mistake when pushing files?
- [ ] I self-reviewed the changes on GitHub, line by line.

**Review by ncontinanza — DISMISSED** [review]

**Comment by Nico-Sanchez** [comment]
> Nice addition, should be the standard for all projects.
> 
> To clarify, the author of this PR should provide info on how he/she tested it? Or is this section intended to provide info to the reviewers on how to test it? (if not, I would add a section with that purpose)
> 
> > ## How has this been tested?
> > Describe the steps you performed to test this PR.
> 

"How has this been tested?" is a section where the author should list the steps he/she performed in order to make sure the PR works as expected. This way, the reviewer gets to know a way to test this PR and also think if there's another path that the author didn't test and could lead to a bug.

I don't recommend adding a section where the author specifies how to test it because the reviewer will be influenced by that and approve the PR if that path works.

> Also, what is the goal of self-reviewing? Making sure you didn't make a mistake when pushing files?
> 
> > I self-reviewed the changes on GitHub, line by line.

Self-reviewing is crucial. Everyone should be the 1st reviewer of him/herself.
This way, we don't make our reviewer lose time for mistakes or wrong changes that are easy to notice if you look at your own changes in the code. Once the author "approves" his/her own changes, then that's when the PR is ready for a review.

**Comment by Nico-Sanchez** [comment]
> I will add a section for the devices, for example:
> 
> * [x]  Tested in Unity Desktop
> * [x]  Tested in Android
> * [ ]  Tested in IOS
> 
> What do you think?

Nice suggestion. I added a checkpoint item where the author can tell that he/she has been tested the PR in mobile (iOS, android).

I didn't put it together with the "tested changes locally" item because I think that's a must, where the others are optional.

Let me know if this suits you.

**Review by manucamejo — APPROVED** [review]

**Review by martinacantaro — COMMENTED** [review]
Thanks for the reply @Nico-Sanchez . Just out of curiosity, what sort of mistakes do you catch with the github self-review? Unnecessary files pushed?

**Review by tvillegas98 — APPROVED** [review]

**Pull request merged**
