### PR TITLE
Character selection updates

### PR DESCRIPTION
**Pull request by AngieDutra**
This PR:

- Fixes scroll in players list
- Makes the confirm button hide when the character is confirmed
- Changes title

### CODE REVIEW

**Review by BertovDev — APPROVED** [review]
Working good! 

- [x] Scroll tested with +10 items
- [x] Selection tested with 2 players
- [x] Tested in Unity Desktop
- [ ] Tested in Android

**Comment by BertovDev** [comment]
Did you tested it in Android ? im currently without battery 😔. If not I can do it later.

**Comment by AngieDutra** [comment]
> Did you tested it in Android ? im currently without battery 😔. If not I can do it later. It looks good in all simulators tho.

I did!

**Comment by BertovDev** [comment]
> > Did you tested it in Android ? im currently without battery 😔. If not I can do it later. It looks good in all simulators tho.
> 
> I did! When I was developing I did several tests with my Android and computer to fake players and test this

Great!🤩

**Review by tvillegas98 — APPROVED** [review]
gud work 👍

**Pull request merged**
