### PR TITLE
Add SkillRange, Shrinking Parameters to Config Files and Restore Muflus Skills

### PR DESCRIPTION
**Pull request by tvillegas98**
This PR adds the following things
### Changes:
- Adds the starting time to the shrink zone in the `GameSettings.json` as `map_shrink_wait_ms`
- Adds the interval time to increase the shrink zone in the `GameSettings.json` as `map_shrink_interval`
- Adds the shrink zone damage as `out_of_area_damage`
- Adds the skill range to the `Skills.json` config file as `SkillRange`
- Adds the angle to the `Skills.json` config file as `Angle`
- The Backend now uses the SkillRange according to what the `Skills.json` says
- Muflus skills are going to be reverted to the state previous #611 

### Disclaimer
- Ignore commits above [a93fb0](https://github.com/lambdaclass/curse_of_myrra/commit/a93fb0de0e2663834f820b71c2884121d34e2f4a). I didn't branch from main 🤦 .

### CODE REVIEW

**Review by marco-paulucci — COMMENTED** [review]
Hi! 

Would you mind documenting the new JSON fields here?
https://github.com/lambdaclass/curse_of_myrra/blob/modify-config-parameters/docs/src/data_fileguides.md

Great work!

**Comment by tvillegas98** [comment]
> Would you mind documenting the new JSON fields here? https://github.com/lambdaclass/curse_of_myrra/blob/modify-config-parameters/docs/src/data_fileguides.md

Yes, no problem! 😄 . I forgot about that. Thanks for the reminder

**Review by manucamejo — APPROVED** [review]
Next time, please create two separate PRs: one for the new fields in the config and the other for Muflus skills.

**Comment by tvillegas98** [comment]
> Next time, please create two separate PRs: one for the new fields in the config and the other for Muflus skills.

You're right!

**Review by jrchatruc — APPROVED** [review]

**Pull request merged**
