### PR TITLE
Add new muflus model

### LINKED ISSUE #842: [REFACTOR] New Muflus model and animations
## 🚧 Refactor

Implement new Muflus model and map each animation.
Files: https://drive.google.com/drive/u/0/folders/1AebR5Y8HU-RxePVr0VhVoBdrowqv-NHr

#### Ready to map
- [x] Idle
- [x] Walking
#### Pending
- Crush (basic)
- Leap (special)
- Winner
- Defeated

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #842 

## Before Reviewing
** List of things we already saw and going to be fixed in another PR in order to merge this PR as soon as possible**

1. Dont mind if the animations in Victory/Death splash are broken. The entire screen its going to be remake.
2. Defeat animation have some problems (it has only one eye )
3. SkillBasic animation dont match the range
4. Heal and Damage effects are not working in this New Muflus ( Ticket had been created )

## Motivation

New Muflus model is now avaible.

## Summary of changes

Added:
- New Muflus Model for game and UI
- Material
- Textures
- Animations

Changed:
- Muflus Prefab have new model
- MainCameraUI and DeathSplash now use's the new MuflusUI model
- Animators have the new Animations linked

Removed:
- Old Muflus model

## How has this been tested?
UI:
1. Go to MainScreen see muflus scale in the screen.

In Game:
1. Pick Muflus.
5. Play as normal, see the animations
6. Die/Win to see the DeathSplash animations

## Test additions / changes

**PLEASE TEST THE MUFLUS IN GAME AND LEAVE THE FOLLOWING FEEDBACK**

- How the Scale look's?
- How the lightning look's?
- How the animation look's?
- How the material look's?

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by tkz00 — CHANGES_REQUESTED** [review]
The model's scale and colors look great, but I've found a few problems:

- It seems there is a problem with the lighting in the Main Scene, the model looks super dark:
Screenshot 2023-11-09 at 09 45 25

- Only when you win, the DeathSplash animation only plays one time an then the model stops moving (this is an image, but it might as well be a video):
Screenshot 2023-11-09 at 09 39 48

- Also as you can see the DeathSplash model gets cropped, both in victory and defeat.

- And this is more of a personal taste matter, I think the attack animation is too fast, it looks weird and also the last part of the animation, when Muflus get's back into position for a next animation, looks like he should already be able to perform another action, but it's unable until the animation is finished. I think it's important to feedback to the player when an action is finished and make it clear when another one can be performed. Maybe blending the end of this animation with the next one can look nice, i know it can be made in Unreal but I don't know about Unity.

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by ncontinanza — DISMISSED** [review]

**Review by tkz00 — CHANGES_REQUESTED** [review]
I think it's important to remove the old Muflus model since we will not longer be using it.

**Review by AngieDutra — CHANGES_REQUESTED** [review]
The new muflus is too big for these screens
Captura de pantalla 2023-11-21 a la(s) 15 54 08
Captura de pantalla 2023-11-21 a la(s) 15 58 10

**Review by tkz00 — APPROVED** [review]
Great work!

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I think Muflus is still too big. Check Dagna, Uma and Hack. Their top is closer to the lightning in the center. Muflus head goes up to the clouds. This wouldn't be such a problem but it's too tall to a point where it dificults pressing the server selector button
Captura de pantalla 2023-11-21 a la(s) 16 33 08

Captura de pantalla 2023-11-21 a la(s) 16 32 52

Captura de pantalla 2023-11-21 a la(s) 16 30 42

**Comment by BertovDev** [comment]
> I think Muflus is still too big. Check Dagna, Uma and Hack. Their top is closer to the lightning in the center. Muflus head goes up to the clouds. This wouldn't be such a problem but it's too tall to a point where it dificults pressing the server selector button Captura de pantalla 2023-11-21 a la(s) 16 33 08
> Captura de pantalla 2023-11-21 a la(s) 16 32 52 Captura de pantalla 2023-11-21 a la(s) 16 30 42

Do we really want every character to fit in the same space? Muflus is bigger than other character and in the game refeences we have they use this method to difference them

**Comment by AngieDutra** [comment]
> > I think Muflus is still too big. Check Dagna, Uma and Hack. Their top is closer to the lightning in the center. Muflus head goes up to the clouds. This wouldn't be such a problem but it's too tall to a point where it dificults pressing the server selector button Captura de pantalla 2023-11-21 a la(s) 16 33 08
> > Captura de pantalla 2023-11-21 a la(s) 16 32 52 Captura de pantalla 2023-11-21 a la(s) 16 30 42
> 
> Do we really want every character to fit in the same space? Muflus is bigger than other character and in the game refeences we have they use this method to difference them

In the UI the goal is to make every character the same size due to UI issues if we don't. For example weird spacings. I checked with the design team and they agree on this

**Review by AngieDutra — APPROVED** [review]
Nice work! ✨

**Review by ncontinanza — APPROVED** [review]

**Pull request merged**
