### PR TITLE
Main screen

### PR DESCRIPTION
**Pull request by AngieDutra**
The new main screen should look like this:
Refe-New
 Check:
- It is usable from title screen to lobbies screen
- The animations size is okey

NOTE: I did a refactor for ui animations that are based off 3d models so you should also check the death splash (victory and defeat animations for each character) are working as expected

### CODE REVIEW

**Review by BertovDev — CHANGES_REQUESTED** [review]
This is awesome and I believe we should not be using Character `prefabs` to be displayed in the screen since their contains scripts we dont need. We should use the `Models`. 

What do you think?

**Review by ncontinanza — APPROVED** [review]
LGTM!

**Review by BertovDev — DISMISSED** [review]

**Review by ncontinanza — CHANGES_REQUESTED** [review]
Looking great! Just an issue in Uma's victory screen, the animation is frozen after the first few seconds

https://github.com/lambdaclass/curse_of_myrra/assets/17294394/6b687cdd-8368-4e25-9f32-784b45636618

**Review by ncontinanza — APPROVED** [review]
Working great!

**Review by BertovDev — APPROVED** [review]
Looks great!

- [x] Tested in Unity Desktop
- [x] Tested in Android

**Pull request merged**
