### PR TITLE
Disable exit button on battle menu

### LINKED ISSUE #1027: [FEATURE] Remove exit game button
## 🚀 Feature
Remove the _Exit game_ button from the battle settings menu.

### PR DESCRIPTION
**Pull request by tkz00**
Disabled the button in the battle menu canvas, didn't delete it, it could be useful for debugging scenarios, it allows to exit and start a new match without having to restart the client.

Closes #1027

### CODE REVIEW

**Review by BertovDev — DISMISSED** [review]

**Review by agustinesco — APPROVED** [review]

**Comment by tkz00** [comment]
Finally instead of removing the exit button I moved it to the developer options since it's a useful tool.

**Review by AngieDutra — CHANGES_REQUESTED** [review]
It is great to still have the exit game in the dev options. However I do have some suggestiond style wise.
Captura de pantalla 2023-10-27 a la(s) 12 50 38

I noticed the buttons changed their sizes. They should be the same size as in main:
image
If you want some help on this do tell! Happy to help ✨

**Comment by tkz00** [comment]
> It is great to still have the exit game in the dev options. However I do have some suggestiond style wise. Captura de pantalla 2023-10-27 a la(s) 12 50 38
> 
> I noticed the buttons changed their sizes. They should be the same size as in main: image If you want some help on this do tell! Happy to help ✨

Resized the buttons in the new commit! Hope it looks good!

**Review by BertovDev — APPROVED** [review]

**Review by AngieDutra — APPROVED** [review]
Good job 🚀

**Pull request merged**
