### PR TITLE
Death splash screen

### LINKED ISSUE #539: [FEATURE] Change camera to follow another player on death

### LINKED ISSUE #573: [FEATURE] Defeated state
If the player is defeated, we should:
- Show an overlay screen with the result of the match (REF1):
  - Back to lobbies button.
  - Match ranking place.
- Make the camera follow an alive character (if its possible, the one who defeated the player).

REF1:
Image

### LINKED ISSUE #635: [BUG] Fix dead and game finished state
We still have to make some changes/validations when a player dies and when the game has finished.

Player dies:
- Shouldn't be able to interact with controls and buttons.
- Character condition state should be 'dead'.

Match ends:
- Winner shouldn't be able to interact with controls and buttons.
- The game should be stopped.

### PR DESCRIPTION
**Pull request by ncontinanza**
Closes #573 
Closes #539 
Closes #635 

This PR implements a screen that's displayed when a player is killed or, in the case of the winner, when the game finishes.

Things to test:
* The screen is only visible when your character is killed or, if you won the match, when you kill the last remaining player.
* In the screen, you should be able to see:
   * Your ranking in the match. 1 for the winner, 2 for the last player to die, and so on.
   * The text "The king of Araban!" if you won, and "Better luck next time!" if you lost.
   * Your total kills.
   * A button that takes you back to the lobbies scene.
* You shouldn't see the joystick and buttons after the screen is activated.
* When the screen activates after you were killed by another player, your camera should be reassigned to any of the other living players. If that player is killed, your camera should be reassigned again, until the match ends.

### CODE REVIEW

**Review by saugon — APPROVED** [review]
Nice job!

**Comment by saugon** [comment]
We still need to improve some things (but in a future PR):
- Allow players to cycle the camera between alive players.
- Toggle 'ended game' ui.
- Client character animation in the left section of the ui.

**Comment by tvillegas98** [comment]
Nice work!

**Review by BertovDev — APPROVED** [review]
This is Awesome! 🤩

**Pull request merged**
